package org.iota.ict.ixi.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FindTransactionsByAddressResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FindTransactionsByAddressResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    java.util.List<Model.Transaction> 
        getTransactionsList();
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    Model.Transaction getTransactions(int index);
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    java.util.List<? extends Model.TransactionOrBuilder> 
        getTransactionsOrBuilderList();
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    Model.TransactionOrBuilder getTransactionsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code FindTransactionsByAddressResponse}
   */
  public  static final class FindTransactionsByAddressResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FindTransactionsByAddressResponse)
      FindTransactionsByAddressResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindTransactionsByAddressResponse.newBuilder() to construct.
    private FindTransactionsByAddressResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindTransactionsByAddressResponse() {
      transactions_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindTransactionsByAddressResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                transactions_ = new java.util.ArrayList<Model.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactions_.add(
                  input.readMessage(Model.Transaction.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_FindTransactionsByAddressResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_FindTransactionsByAddressResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FindTransactionsByAddressResponse.class, Builder.class);
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 1;
    private java.util.List<Model.Transaction> transactions_;
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<Model.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<? extends Model.TransactionOrBuilder> 
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Model.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Model.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(1, transactions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transactions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FindTransactionsByAddressResponse)) {
        return super.equals(obj);
      }
      FindTransactionsByAddressResponse other = (FindTransactionsByAddressResponse) obj;

      if (!getTransactionsList()
          .equals(other.getTransactionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FindTransactionsByAddressResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionsByAddressResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionsByAddressResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FindTransactionsByAddressResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FindTransactionsByAddressResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FindTransactionsByAddressResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FindTransactionsByAddressResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FindTransactionsByAddressResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FindTransactionsByAddressResponse)
        FindTransactionsByAddressResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_FindTransactionsByAddressResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_FindTransactionsByAddressResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FindTransactionsByAddressResponse.class, Builder.class);
      }

      // Construct using Response.FindTransactionsByAddressResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_FindTransactionsByAddressResponse_descriptor;
      }

      @Override
      public FindTransactionsByAddressResponse getDefaultInstanceForType() {
        return FindTransactionsByAddressResponse.getDefaultInstance();
      }

      @Override
      public FindTransactionsByAddressResponse build() {
        FindTransactionsByAddressResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FindTransactionsByAddressResponse buildPartial() {
        FindTransactionsByAddressResponse result = new FindTransactionsByAddressResponse(this);
        int from_bitField0_ = bitField0_;
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FindTransactionsByAddressResponse) {
          return mergeFrom((FindTransactionsByAddressResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FindTransactionsByAddressResponse other) {
        if (other == FindTransactionsByAddressResponse.getDefaultInstance()) return this;
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FindTransactionsByAddressResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FindTransactionsByAddressResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Model.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          transactions_ = new java.util.ArrayList<Model.Transaction>(transactions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public java.util.List<Model.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addAllTransactions(
          Iterable<? extends Model.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public java.util.List<? extends Model.TransactionOrBuilder> 
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            Model.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, Model.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public java.util.List<Model.Transaction.Builder> 
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FindTransactionsByAddressResponse)
    }

    // @@protoc_insertion_point(class_scope:FindTransactionsByAddressResponse)
    private static final FindTransactionsByAddressResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FindTransactionsByAddressResponse();
    }

    public static FindTransactionsByAddressResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindTransactionsByAddressResponse>
        PARSER = new com.google.protobuf.AbstractParser<FindTransactionsByAddressResponse>() {
      @Override
      public FindTransactionsByAddressResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindTransactionsByAddressResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindTransactionsByAddressResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FindTransactionsByAddressResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public FindTransactionsByAddressResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindTransactionsByTagResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FindTransactionsByTagResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    java.util.List<Model.Transaction> 
        getTransactionsList();
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    Model.Transaction getTransactions(int index);
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    java.util.List<? extends Model.TransactionOrBuilder> 
        getTransactionsOrBuilderList();
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    Model.TransactionOrBuilder getTransactionsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code FindTransactionsByTagResponse}
   */
  public  static final class FindTransactionsByTagResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FindTransactionsByTagResponse)
      FindTransactionsByTagResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindTransactionsByTagResponse.newBuilder() to construct.
    private FindTransactionsByTagResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindTransactionsByTagResponse() {
      transactions_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindTransactionsByTagResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                transactions_ = new java.util.ArrayList<Model.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactions_.add(
                  input.readMessage(Model.Transaction.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_FindTransactionsByTagResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_FindTransactionsByTagResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FindTransactionsByTagResponse.class, Builder.class);
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 1;
    private java.util.List<Model.Transaction> transactions_;
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<Model.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<? extends Model.TransactionOrBuilder> 
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Model.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Model.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(1, transactions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transactions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FindTransactionsByTagResponse)) {
        return super.equals(obj);
      }
      FindTransactionsByTagResponse other = (FindTransactionsByTagResponse) obj;

      if (!getTransactionsList()
          .equals(other.getTransactionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FindTransactionsByTagResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionsByTagResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionsByTagResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionsByTagResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionsByTagResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionsByTagResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionsByTagResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FindTransactionsByTagResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FindTransactionsByTagResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FindTransactionsByTagResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FindTransactionsByTagResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FindTransactionsByTagResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FindTransactionsByTagResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FindTransactionsByTagResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FindTransactionsByTagResponse)
        FindTransactionsByTagResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_FindTransactionsByTagResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_FindTransactionsByTagResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FindTransactionsByTagResponse.class, Builder.class);
      }

      // Construct using Response.FindTransactionsByTagResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_FindTransactionsByTagResponse_descriptor;
      }

      @Override
      public FindTransactionsByTagResponse getDefaultInstanceForType() {
        return FindTransactionsByTagResponse.getDefaultInstance();
      }

      @Override
      public FindTransactionsByTagResponse build() {
        FindTransactionsByTagResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FindTransactionsByTagResponse buildPartial() {
        FindTransactionsByTagResponse result = new FindTransactionsByTagResponse(this);
        int from_bitField0_ = bitField0_;
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FindTransactionsByTagResponse) {
          return mergeFrom((FindTransactionsByTagResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FindTransactionsByTagResponse other) {
        if (other == FindTransactionsByTagResponse.getDefaultInstance()) return this;
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FindTransactionsByTagResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FindTransactionsByTagResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Model.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          transactions_ = new java.util.ArrayList<Model.Transaction>(transactions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public java.util.List<Model.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder addAllTransactions(
          Iterable<? extends Model.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public java.util.List<? extends Model.TransactionOrBuilder> 
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            Model.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, Model.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .Transaction transactions = 1;</code>
       */
      public java.util.List<Model.Transaction.Builder> 
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FindTransactionsByTagResponse)
    }

    // @@protoc_insertion_point(class_scope:FindTransactionsByTagResponse)
    private static final FindTransactionsByTagResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FindTransactionsByTagResponse();
    }

    public static FindTransactionsByTagResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindTransactionsByTagResponse>
        PARSER = new com.google.protobuf.AbstractParser<FindTransactionsByTagResponse>() {
      @Override
      public FindTransactionsByTagResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindTransactionsByTagResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindTransactionsByTagResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FindTransactionsByTagResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public FindTransactionsByTagResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindTransactionByHashResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FindTransactionByHashResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Transaction transactions = 1;</code>
     */
    boolean hasTransactions();
    /**
     * <code>.Transaction transactions = 1;</code>
     */
    Model.Transaction getTransactions();
    /**
     * <code>.Transaction transactions = 1;</code>
     */
    Model.TransactionOrBuilder getTransactionsOrBuilder();
  }
  /**
   * Protobuf type {@code FindTransactionByHashResponse}
   */
  public  static final class FindTransactionByHashResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FindTransactionByHashResponse)
      FindTransactionByHashResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindTransactionByHashResponse.newBuilder() to construct.
    private FindTransactionByHashResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindTransactionByHashResponse() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindTransactionByHashResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Model.Transaction.Builder subBuilder = null;
              if (transactions_ != null) {
                subBuilder = transactions_.toBuilder();
              }
              transactions_ = input.readMessage(Model.Transaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactions_);
                transactions_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_FindTransactionByHashResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_FindTransactionByHashResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FindTransactionByHashResponse.class, Builder.class);
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 1;
    private Model.Transaction transactions_;
    /**
     * <code>.Transaction transactions = 1;</code>
     */
    public boolean hasTransactions() {
      return transactions_ != null;
    }
    /**
     * <code>.Transaction transactions = 1;</code>
     */
    public Model.Transaction getTransactions() {
      return transactions_ == null ? Model.Transaction.getDefaultInstance() : transactions_;
    }
    /**
     * <code>.Transaction transactions = 1;</code>
     */
    public Model.TransactionOrBuilder getTransactionsOrBuilder() {
      return getTransactions();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (transactions_ != null) {
        output.writeMessage(1, getTransactions());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (transactions_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTransactions());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FindTransactionByHashResponse)) {
        return super.equals(obj);
      }
      FindTransactionByHashResponse other = (FindTransactionByHashResponse) obj;

      if (hasTransactions() != other.hasTransactions()) return false;
      if (hasTransactions()) {
        if (!getTransactions()
            .equals(other.getTransactions())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTransactions()) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactions().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FindTransactionByHashResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionByHashResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionByHashResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionByHashResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionByHashResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FindTransactionByHashResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FindTransactionByHashResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FindTransactionByHashResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FindTransactionByHashResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FindTransactionByHashResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FindTransactionByHashResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FindTransactionByHashResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FindTransactionByHashResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FindTransactionByHashResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FindTransactionByHashResponse)
        FindTransactionByHashResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_FindTransactionByHashResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_FindTransactionByHashResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FindTransactionByHashResponse.class, Builder.class);
      }

      // Construct using Response.FindTransactionByHashResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (transactionsBuilder_ == null) {
          transactions_ = null;
        } else {
          transactions_ = null;
          transactionsBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_FindTransactionByHashResponse_descriptor;
      }

      @Override
      public FindTransactionByHashResponse getDefaultInstanceForType() {
        return FindTransactionByHashResponse.getDefaultInstance();
      }

      @Override
      public FindTransactionByHashResponse build() {
        FindTransactionByHashResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FindTransactionByHashResponse buildPartial() {
        FindTransactionByHashResponse result = new FindTransactionByHashResponse(this);
        if (transactionsBuilder_ == null) {
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FindTransactionByHashResponse) {
          return mergeFrom((FindTransactionByHashResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FindTransactionByHashResponse other) {
        if (other == FindTransactionByHashResponse.getDefaultInstance()) return this;
        if (other.hasTransactions()) {
          mergeTransactions(other.getTransactions());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FindTransactionByHashResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FindTransactionByHashResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Model.Transaction transactions_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder> transactionsBuilder_;
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public boolean hasTransactions() {
        return transactionsBuilder_ != null || transactions_ != null;
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Model.Transaction getTransactions() {
        if (transactionsBuilder_ == null) {
          return transactions_ == null ? Model.Transaction.getDefaultInstance() : transactions_;
        } else {
          return transactionsBuilder_.getMessage();
        }
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactions_ = value;
          onChanged();
        } else {
          transactionsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          Model.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          transactions_ = builderForValue.build();
          onChanged();
        } else {
          transactionsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Builder mergeTransactions(Model.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (transactions_ != null) {
            transactions_ =
              Model.Transaction.newBuilder(transactions_).mergeFrom(value).buildPartial();
          } else {
            transactions_ = value;
          }
          onChanged();
        } else {
          transactionsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = null;
          onChanged();
        } else {
          transactions_ = null;
          transactionsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Model.Transaction.Builder getTransactionsBuilder() {
        
        onChanged();
        return getTransactionsFieldBuilder().getBuilder();
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      public Model.TransactionOrBuilder getTransactionsOrBuilder() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilder();
        } else {
          return transactions_ == null ?
              Model.Transaction.getDefaultInstance() : transactions_;
        }
      }
      /**
       * <code>.Transaction transactions = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Model.Transaction, Model.Transaction.Builder, Model.TransactionOrBuilder>(
                  getTransactions(),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FindTransactionByHashResponse)
    }

    // @@protoc_insertion_point(class_scope:FindTransactionByHashResponse)
    private static final FindTransactionByHashResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FindTransactionByHashResponse();
    }

    public static FindTransactionByHashResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindTransactionByHashResponse>
        PARSER = new com.google.protobuf.AbstractParser<FindTransactionByHashResponse>() {
      @Override
      public FindTransactionByHashResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindTransactionByHashResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindTransactionByHashResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FindTransactionByHashResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public FindTransactionByHashResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DetermineApprovalConfidenceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DetermineApprovalConfidenceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double approvalConfidence = 1;</code>
     */
    double getApprovalConfidence();
  }
  /**
   * Protobuf type {@code DetermineApprovalConfidenceResponse}
   */
  public  static final class DetermineApprovalConfidenceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DetermineApprovalConfidenceResponse)
      DetermineApprovalConfidenceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DetermineApprovalConfidenceResponse.newBuilder() to construct.
    private DetermineApprovalConfidenceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DetermineApprovalConfidenceResponse() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DetermineApprovalConfidenceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              approvalConfidence_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_DetermineApprovalConfidenceResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_DetermineApprovalConfidenceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DetermineApprovalConfidenceResponse.class, Builder.class);
    }

    public static final int APPROVALCONFIDENCE_FIELD_NUMBER = 1;
    private double approvalConfidence_;
    /**
     * <code>double approvalConfidence = 1;</code>
     */
    public double getApprovalConfidence() {
      return approvalConfidence_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (approvalConfidence_ != 0D) {
        output.writeDouble(1, approvalConfidence_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (approvalConfidence_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, approvalConfidence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DetermineApprovalConfidenceResponse)) {
        return super.equals(obj);
      }
      DetermineApprovalConfidenceResponse other = (DetermineApprovalConfidenceResponse) obj;

      if (Double.doubleToLongBits(getApprovalConfidence())
          != Double.doubleToLongBits(
              other.getApprovalConfidence())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPROVALCONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getApprovalConfidence()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DetermineApprovalConfidenceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DetermineApprovalConfidenceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DetermineApprovalConfidenceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DetermineApprovalConfidenceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DetermineApprovalConfidenceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DetermineApprovalConfidenceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DetermineApprovalConfidenceResponse)
        DetermineApprovalConfidenceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_DetermineApprovalConfidenceResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_DetermineApprovalConfidenceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DetermineApprovalConfidenceResponse.class, Builder.class);
      }

      // Construct using Response.DetermineApprovalConfidenceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        approvalConfidence_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_DetermineApprovalConfidenceResponse_descriptor;
      }

      @Override
      public DetermineApprovalConfidenceResponse getDefaultInstanceForType() {
        return DetermineApprovalConfidenceResponse.getDefaultInstance();
      }

      @Override
      public DetermineApprovalConfidenceResponse build() {
        DetermineApprovalConfidenceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DetermineApprovalConfidenceResponse buildPartial() {
        DetermineApprovalConfidenceResponse result = new DetermineApprovalConfidenceResponse(this);
        result.approvalConfidence_ = approvalConfidence_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DetermineApprovalConfidenceResponse) {
          return mergeFrom((DetermineApprovalConfidenceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DetermineApprovalConfidenceResponse other) {
        if (other == DetermineApprovalConfidenceResponse.getDefaultInstance()) return this;
        if (other.getApprovalConfidence() != 0D) {
          setApprovalConfidence(other.getApprovalConfidence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DetermineApprovalConfidenceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DetermineApprovalConfidenceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double approvalConfidence_ ;
      /**
       * <code>double approvalConfidence = 1;</code>
       */
      public double getApprovalConfidence() {
        return approvalConfidence_;
      }
      /**
       * <code>double approvalConfidence = 1;</code>
       */
      public Builder setApprovalConfidence(double value) {
        
        approvalConfidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double approvalConfidence = 1;</code>
       */
      public Builder clearApprovalConfidence() {
        
        approvalConfidence_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DetermineApprovalConfidenceResponse)
    }

    // @@protoc_insertion_point(class_scope:DetermineApprovalConfidenceResponse)
    private static final DetermineApprovalConfidenceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DetermineApprovalConfidenceResponse();
    }

    public static DetermineApprovalConfidenceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetermineApprovalConfidenceResponse>
        PARSER = new com.google.protobuf.AbstractParser<DetermineApprovalConfidenceResponse>() {
      @Override
      public DetermineApprovalConfidenceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DetermineApprovalConfidenceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DetermineApprovalConfidenceResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DetermineApprovalConfidenceResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public DetermineApprovalConfidenceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindTransactionsByAddressResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindTransactionsByAddressResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindTransactionsByTagResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindTransactionsByTagResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindTransactionByHashResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindTransactionByHashResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DetermineApprovalConfidenceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DetermineApprovalConfidenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016response.proto\032\013model.proto\"G\n!FindTra" +
      "nsactionsByAddressResponse\022\"\n\014transactio" +
      "ns\030\001 \003(\0132\014.Transaction\"C\n\035FindTransactio" +
      "nsByTagResponse\022\"\n\014transactions\030\001 \003(\0132\014." +
      "Transaction\"C\n\035FindTransactionByHashResp" +
      "onse\022\"\n\014transactions\030\001 \001(\0132\014.Transaction" +
      "\"A\n#DetermineApprovalConfidenceResponse\022" +
      "\032\n\022approvalConfidence\030\001 \001(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Model.getDescriptor(),
        }, assigner);
    internal_static_FindTransactionsByAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FindTransactionsByAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindTransactionsByAddressResponse_descriptor,
        new String[] { "Transactions", });
    internal_static_FindTransactionsByTagResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FindTransactionsByTagResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindTransactionsByTagResponse_descriptor,
        new String[] { "Transactions", });
    internal_static_FindTransactionByHashResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FindTransactionByHashResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindTransactionByHashResponse_descriptor,
        new String[] { "Transactions", });
    internal_static_DetermineApprovalConfidenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DetermineApprovalConfidenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DetermineApprovalConfidenceResponse_descriptor,
        new String[] { "ApprovalConfidence", });
    Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
